### PR TITLE
Make 'Resource Grind' quest barrel retrieval.

### PR DESCRIPTION
**Pull request by NabilZaman**

### CODE REVIEW

**Comment by tecrogue** [comment]
It's deliberate how it is set. 

Feedback on quests would be better received in the discord, not as a pull request.

**Comment by NabilZaman** [comment]
Was taking a look at the issue backlog, took a guess that the issue regarding this was being considered and just not implemented as it wasn't a priority.

But fair enough.

**Comment by tecrogue** [comment]
Sorry about that, I had thought that one had been closed a while back honestly and didn't see that it was still open until after my initial reply.

Right now the main focus is testing the pending update to make sure it took care of the existing issues.

One issue that has been a thorn that I am struggling with is the maps don't always load on creation of a new world in single player. Not sure if that is something you would be interested in looking into, but it would be quite the help if you discovered what was causing that.

**Comment by NabilZaman** [comment]
No worries.
I don't want to oversell my competency with modpack development: I have none.
My motivations with poking around here were mostly selfish in trying to confirm there were no game-breaking issues in the latest version before I made a server for my friends to play on.

But if I do by some dumb-luck happen across a fix, I'll be sure to push a patch.

**Comment by tecrogue** [comment]
Haha that's how I initially became involved myself.

I appreciate that you are comparing commits to specific issues. Right now we are light on testers and I haven't had a chance to personally test the release candidate against the open issues (we lost the person who was previously working on the update before it was finished sadly).

If you are on the discord and would be interested in testing the release candidate against the current issues I'd be happy to give you access to the testing channel with it.

**Pull request closed without merging**
